Revert "lmb: consider EFI memory map"
The efi_lmb_reserve() function marks memory up to 0x7fffffff and from
0x800000000 to 0x87fffffff as reserved.

However, when boot_fdt_reserve_region() attempts to reserve the
overlapping region 0x800000000 to 0x87fffffff, an error occurs
because LMB recognizes that this region is already reserved.

To address the below errors :
ERROR: reserving fdt memory region failed (addr=800000000 size=80000000 flags=4)
ERROR: reserving fdt memory region failed (addr=50000000000 size=200000000 flags=4)

The workaround is to revert commit: 06d514d77c

Signed-off-by: Tejas Bhumkar <tejas.arvind.bhumkar@amd.com>
State: not-upstreamable