mtd: spi-nor: Remove SPI_FLASH_STMICRO #if defined directive
Resolve compilation error when building with zynq_cse_nor & zynq_cse_nand
defconfig files. Below error is due to undefined SPI_FLASH_STMICRO config
and micron_octal_ddr_enable() not being compiled.

drivers/mtd/spi/spi-nor-core.c:2717:27: error: 'micron_octal_ddr_enable'
undeclared (first use in this function)
	2717 |   nor->octal_ddr_enable = micron_octal_ddr_enable;

So remove the SPI_FLASH_STMICRO #if defined directive to compile
micron_octal_ddr_enable() with above defined defconfig files.

Signed-off-by: T Karthik Reddy <t.karthik.reddy@xilinx.com>
Reviewed-by: Ashok Reddy Soma <ashok.reddy.soma@xilinx.com>
State: pending