xilinx: versal-net: Add missing COUNTER_FREQUENCY for mini mtest
Add missing macro to remove compilation error caused by commit f10309981db3
("xilinx: versal-net: Add support for timer and start it").

Error log:
board/xilinx/versal-net/board.c: In function 'board_early_init_r':
board/xilinx/versal-net/board.c:151:16: error: 'COUNTER_FREQUENCY' undeclared
 (first use in this function); did you mean 'CONFIG_COUNTER_FREQUENCY'?

Signed-off-by: Michal Simek <michal.simek@amd.com>