fix compilation error due to missing object
error:
arm-xilinxa9-linux-gnueabi-objdump: 'board/xilinx/dfe/libdfe.o': No such file
arm-xilinxa9-linux-gnueabi-objdump: 'arch/arm/cpu/armv7/pele/libpele.o': No such file
arm-xilinxa9-linux-gnueabi-ld: cannot find arch/arm/cpu/armv7/pele/libpele.o: No such file or directory