mtd: spi-nor: Fix build issue for stmark2_defconfig
When building stmark2_defconfig, an issue occurred due to the missing
asm/gpio.h. To resolve this, the generic header file asm-generic/gpio.h
was added. Additionally, checks were added in spi_nor_hw_reset() so
that when CONFIG_IS_ENABLED(DM_GPIO) is enabled, the function executes
the corresponding code otherwise, it simply returns zero.

drivers/mtd/spi/spi-nor-core.c:15:10: fatal error: asm/gpio.h: No such
file or directory
   15 | #include <asm/gpio.h>

Signed-off-by: Prasad Kummari <prasad.kummari@amd.com>
Message-ID: <20250324085503.3762437-1-prasad.kummari@amd.com>
State: pending