Revert "lmb: consider EFI memory map"
This reverts commit 06d514d77c3700ec6166457f58d37652791038d0.
This is workaround to fix the below errors
ERROR: reserving fdt memory region failed (addr=800000000 size=180000000 flags=4)
ERROR: reserving fdt memory region failed (addr=50000000000 size=200000000 flags=4)

Signed-off-by: Ashok Reddy Soma <ashok.reddy.soma@xilinx.com>
Signed-off-by: Venkatesh Yadav Abbarapu <venkatesh.abbarapu@amd.com>
Link: https://lore.kernel.org/r/20230212150706.2967007-1-sjoerd@collabora.com
State: not-upstreamable