common: fdt: replace error prints to debug
When boot_fdt_reserve_region() attempts to reserve the overlapping region
from 0x800000000 to 0x87fffffff, an error occurs because LMB recognizes
that this region is already reserved. Since the u-boot code doesn't perform
any operations specific to reversed nodes although it's an "error" message,
this message can probably be ignored because it's attempting to set the
reserve flag for the memory block/region; success or failure does nothing
other than display messages. Since this routine has a void return type, no
return code is passed back. So, the error message is replaced by debug.

To address the below errors :
    ERROR: reserving fdt memory region failed (addr=800000000 size=80000000 flags=4)
    ERROR: reserving fdt memory region failed (addr=50000000000 size=200000000 flags=4)

Signed-off-by: Prasad Kummari <prasad.kummari@amd.com>
State: not-upstreamable